services:
  ui:
    image: beachcoder/external:9
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER="http://backend:8082"
    depends_on:
      - "backend"
      
  backend:
    image: beachcoder/internal:9
    build:
      context: ../internal
      dockerfile: ../internal/Dockerfile
    ports:
      - "8082:8082"
